//
//  Client.swift
//  kronor-test-app
//
//  Created by Jose-JORO on 2023-01-03.
//

import Foundation
import Apollo
import KronorApi

let merchantToken = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOiAxNjkxMzE2OTQ2LjkyNjIxNiwgImlhdCI6IDE2ODM2MjczNDYuOTI2MjE2LCAidGlkIjogIjBhMTlmY2IzLTk5NWUtNGE2Yy05MGNhLWU1YjlhNDJmYzFkYyIsICJ0bmFtZSI6ICJzdG9yZWZyb250IHY4IiwgInR0eXBlIjogImJhY2tlbmQiLCAiYXNzb2NpYXRlZF9lbWFpbCI6ICJwcmFuYXkuc2FzaGFua0Brcm9ub3IuaW8iLCAiaHR0cHM6Ly9oYXN1cmEuaW8vand0L2NsYWltcyI6IHsieC1oYXN1cmEtdXNlciI6ICJwcmFuYXkuc2FzaGFua0Brcm9ub3IuaW8iLCAieC1oYXN1cmEtbWVyY2hhbnQtaWQiOiAiMiIsICJ4LWhhc3VyYS1kZWZhdWx0LXJvbGUiOiAibWVyY2hhbnQtYmFja2VuZCIsICJ4LWhhc3VyYS1hbGxvd2VkLXJvbGVzIjogWyJtZXJjaGFudC1iYWNrZW5kIl19fQ.8jf_JdG6Wu0THYFsKySQvSeKSwFOFYGoTSB0UAG9IDQ"
func makeGraphQLClientForTestMerchant() -> ApolloClient {
    return KronorApi.makeGraphQLClient(env: .sandbox, token: merchantToken)
}

