//
//  Client.swift
//  kronor-test-app
//
//  Created by Jose-JORO on 2023-01-03.
//

import Foundation
import Apollo
import KronorApi

let merchantToken = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOiAxNjgwNDMyMzgwLjcwNzcxNywgImlhdCI6IDE2NzI5MTU1ODAuNzA3NzE3LCAidGlkIjogIjZkYmMxZWU4LTcyZWYtNDIwZC05YWZiLWJiMDFhMzI0ZTZkYyIsICJ0bmFtZSI6ICJ0ZXN0IGlPUyBhcHAiLCAidHR5cGUiOiAiYmFja2VuZCIsICJhc3NvY2lhdGVkX2VtYWlsIjogImxvcmVuem9Aa3Jvbm9yLmlvIiwgImh0dHBzOi8vaGFzdXJhLmlvL2p3dC9jbGFpbXMiOiB7IngtaGFzdXJhLXVzZXIiOiAibG9yZW56b0Brcm9ub3IuaW8iLCAieC1oYXN1cmEtbWVyY2hhbnQtaWQiOiAiMiIsICJ4LWhhc3VyYS1kZWZhdWx0LXJvbGUiOiAibWVyY2hhbnQtYmFja2VuZCIsICJ4LWhhc3VyYS1hbGxvd2VkLXJvbGVzIjogWyJtZXJjaGFudC1iYWNrZW5kIl19fQ.PIfitgtT1EIvvvwprfWB9wpEPLURKiW6q6Xh9iiurLk"

func makeGraphQLClientForTestMerchant() -> ApolloClient {
    return KronorApi.makeGraphQLClient(token: merchantToken)
}

